
services:
  web:
    build:
      context: .
      dockerfile: DockerFile
    command: bash -c "cd source/ && python manage.py runserver 0.0.0.0:8001"
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8001"
    depends_on:
      - db
      - redis
    env_file:
      - source/.env

  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - source/.env

  redis:
    image: "redis:alpine"
    volumes:
      - "redis_data:/data"
    env_file:
      - source/.env

volumes:
  postgres_data:
  redis_data: